// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBny5FoNcVV7NIiNiIF30MBhN3g6ryE2R8',
    appId: '1:995356823510:web:0d49fb41d0f3d039a6de77',
    messagingSenderId: '995356823510',
    projectId: 'fakhravari',
    authDomain: 'fakhravari.firebaseapp.com',
    storageBucket: 'fakhravari.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlV7fAsXxQzUtXVFckhT6MpnIuF6kWbY',
    appId: '1:995356823510:android:2a9f53819fd9f57ba6de77',
    messagingSenderId: '995356823510',
    projectId: 'fakhravari',
    storageBucket: 'fakhravari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV2ckYwXcQtYQUsmhhFZF5RvrxkzOB308',
    appId: '1:995356823510:ios:268542cd0dff9e77a6de77',
    messagingSenderId: '995356823510',
    projectId: 'fakhravari',
    storageBucket: 'fakhravari.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV2ckYwXcQtYQUsmhhFZF5RvrxkzOB308',
    appId: '1:995356823510:ios:268542cd0dff9e77a6de77',
    messagingSenderId: '995356823510',
    projectId: 'fakhravari',
    storageBucket: 'fakhravari.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBny5FoNcVV7NIiNiIF30MBhN3g6ryE2R8',
    appId: '1:995356823510:web:d1fc73ef6d621e4ca6de77',
    messagingSenderId: '995356823510',
    projectId: 'fakhravari',
    authDomain: 'fakhravari.firebaseapp.com',
    storageBucket: 'fakhravari.appspot.com',
  );

}